{% set name = "dram-viz" %}
{% set version = "0.1.8" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/WrightonLabCSU/dram-viz/archive/{{ version }}.tar.gz
  sha256: 161160adb16e2783ed5dab53d35305f5162dd5a6c5b0427ddc1494017d62bf21

build:
  noarch: python
  entry_points:
    - dram_viz = dram_viz.__main__:main
    - dram.viz = dram_viz.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - bokeh >=3.0,<4
    - panel >=1.0,<2
    - click <9
    - numpy <2
    - networkx >=2,<3
    - panel-jstree >=0.3.5,<0.4.0
    - pandas >=1.2,<3

test:
  imports:
    - dram_viz
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/WrightonLabCSU/dram-viz
  summary: A library for visualizing the output of DRAM v2
  description: |
    The visualization code is used to generate the figures and dashboards for the DRAM v2 gene annotation tool.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/WrightonLabCSU/dram-viz

extra:
  recipe-maintainers:
    - madeline-scyphers
